pipeline {
    agent any
    environment {
        GIT_CREDENTIALS_ID = 'github-credentials'
        BRANCH = 'main'
        DIR_TO_PUSH = '/var/jenkins_home/workspace/testing1'
    }
    stages {
        stage('Stage-1: Clear old files'){
            steps {
                deleteDir()
            }
        }
        stage('Stage-2: Clone repository') {
            steps {
                bat '''
                        rmdir /s /q repo
                        git clone https://github.com/sagar-harry/Testing_Jenkins repo
                        git clone https://github.com/sagar-harry/Testing_Jenkins_2 destination_repo
                    '''
            }
        }
        
        stage("Stage-3: Generate test scripts") {
            steps {
                script {
                    def venv_path = "C:/Users/Administrator/Desktop/QE_COE/genai_venv/Scripts"
                    def workspace_path = "C:/Users/Administrator/Desktop/QE_COE/automated_pipeline"

                    bat """
                        cd ${venv_path}
                        call activate
                        cd ${workspace_path}
                        python generate_test_scripts.py
                    """
                    echo "Completed Stage-3"
                }
            }
        }

        stage("Stage-4: Move generated test scripts") {
            steps {
                script {
                    def venv_path = "C:/Users/Administrator/Desktop/QE_COE/genai_venv/Scripts"
                    def workspace_path = "C:/Users/Administrator/Desktop/QE_COE/automated_pipeline"

                    bat """
                        cd ${venv_path}
                        call activate
                        cd ${workspace_path}
                        python move_test_scripts.py
                    """
                    echo "Completed Stage-4"
                }
            }
        }

        stage('Stage-5: Commit and Push') {
            steps {
                withCredentials([
                    gitUsernamePassword(credentialsId: 'github-credentials', gitToolName: 'Default')
                ]) {
                    bat '''
                    cd destination_repo
                    git config --global user.email "10vidyasagarkonni@gmail.com"
                    git config --global user.name "sagar-harry"
                    git add .
                    git commit -m "Push test scripts"
                    git push origin main
                    '''
                }
            }
        }

        stage("Stage-6: Run test scripts") {
            steps {
                script {
                    def venv_path = "C:/Users/Administrator/Desktop/QE_COE/genai_venv/Scripts"
                    def workspace_path = "C:/Users/Administrator/Desktop/QE_COE/automated_pipeline"

                    bat """
                        cd ${venv_path}
                        call activate
                        cd ${workspace_path}
                        python test_scenarios.py
                    """
                    echo "Completed Stage-6"
                }
            }
        }

        stage("Stage-7: Create xml results") {
            steps {
                script {
                    def venv_path = "C:/Users/Administrator/Desktop/QE_COE/genai_venv/Scripts"
                    def workspace_path = "C:/Users/Administrator/Desktop/QE_COE/automated_pipeline"

                    bat """
                        cd ${venv_path}
                        call activate
                        cd ${workspace_path}
                        python generate_xml_result.py
                    """
                    echo "Completed Stage-7"
                }
            }
        }
        stage('Stage-8: Commit and Push') {
            steps {
                withCredentials([
                    gitUsernamePassword(credentialsId: 'github-credentials', gitToolName: 'Default')
                ]) {
                    bat '''
                    cd destination_repo
                    git config --global user.email "10vidyasagarkonni@gmail.com"
                    git config --global user.name "sagar-harry"
                    git add .
                    git commit -m "Push test results"
                    git push origin main
                    '''
                }
            }
        }

        
    }
}
